doing smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -368,9 +368,9 @@ jobs:
             if curl -s "${API_URL}/api/status" | grep "ok"
             then
               echo "backend is working successfully"
-              return 0
+              exit 0
             else
-              return 1
+              exit 1
             fi
       - run:
           name: Frontend smoke test.
@@ -380,9 +380,9 @@ jobs:
             if curl -s ${URL} | grep "Welcome"
             then
               echo "Frontend is working successfully"
-              return 0
+              exit 0
             else
-              return 1
+              exit 1
             fi
       # Here's where you will add some code to rollback on failure  
       - destroy-environment:
@@ -413,26 +413,66 @@ jobs:
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
       - revert-migrations      
-    #   # Here's where you will add some code to rollback on failure  
+      # Here's where you will add some code to rollback on failure  
 
-# cleanup:
-    # docker:
-    #   # Docker image here
-    # steps:
-    #   # Checkout code from git
-    #   - run:
-    #       name: Get old stack workflow id
-    #       command: |
-    #         # your code here
-    #         export OldWorkflowID="the id here"
-    #         export STACKS=[] #put the list of stacks here
-    #   - run:
-    #       name: Remove old stacks and files
-    #       command: |
-    #         if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-    #         then
-    #           # your code here
-    #         fi
+cleanup:
+    docker:
+      - image: amazon/aws-cli
+    steps:
+      - checkout
+      - run:
+          name: Get old stack workflow id
+          command: |
+            # your code here
+            export OldWorkflowID=<<pipline.parameters.workflow_id>>
+            export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+            --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
+      - run:
+          name: Remove old stacks and files
+          command: |
+            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+            then
+              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+            fi
+
+
+  # cleanup:
+  #   docker:
+  #     - image: cimg/base:stable
+  #   steps:
+  #     - checkout
+  #     - attach_workspace:
+  #         at: ~/
+  #     - run:
+  #         name: Install dependencies
+  #         command: |
+  #           # install AWS CLI
+  #           curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+  #           unzip awscliv2.zip
+  #           sudo ./aws/install
+  #     - run:
+  #         name: Remove old stacks and files
+  #         command: |
+  #           OldWorkflowID=$(cat ~/OldWorkflowID.txt)
+  #           echo OldWorkflowID: "${OldWorkflowID}"
+  #           echo Current_CIRCLE_WORKFLOW_ID: "${CIRCLE_WORKFLOW_ID:0:7}"
+
+  #           export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+  #                   --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
+  #           echo Stack names: "${STACKS[@]}"       
+            
+
+  #           if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+  #           then
+  #             echo "------------------ Deleting old Envirments ------------------"
+  #             aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+  #             aws s3 rm s3://udapeople-${OldWorkflowID} --recursive
+  #             aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+  #           else
+  #             echo "------------------ Nothing to Delete/Can't Delete ------------------"  
+  #           fi
             
 ############################# WORKFLOWS ######################################
 workflows:
